### ISSUE TITLE
GrandMA toggle issue

### ISSUE THREAD

**Issue by marklneumann** [bitfocus/companion-module-grandma2#3]
Working on setting up my Stream Deck to trigger GrandMA2.  I can set a button on the GUI to perform the action "toggle exec 2.101". When I test the button via the GUI it responds as expected, toggling the executor on with a press and then off with a press.  However when I push the actual button on my Stream Deck unit, the button works only as a Go or On.  It does not toggle on and then off.

I am new to the unit so guessing I am just missing something obvious but not seeing anything at this point, and odd that it does work via the GUI.

Thoughts?

**Comment by jbucky86** [comment]
Put the same cmd on the release of the button. What companion is do it pushing the button. If companion never sends a release command the button is still being pushed. If you look on gma it will appear that you are still holding the button. Both programs are acting as the should be

**Comment by jbucky86** [comment]
Oh disregard that I miss read it. What’s the exact command your typing in companion?

If it is “toggle off exec x.x” that won’t work
