### ISSUE TITLE
Numeric Hardkeys don't work and typo on + key

### ISSUE THREAD

**Issue by jifop** [bitfocus/companion-module-grandma2#5]
Looking at MA system monitor the "+" key has a typo from bitfocus, this should be "PLUS" but is sending "PLUSE"

Also numeric Hardkeys don't seem to work at all.

**Comment by jifop** [comment]
I've tested the LUA commands directly e.g gma.canbus.hardkey(86, true, false)
gma.canbus.hardkey(86, false, false)

This definitely replicates the numeric "0" key 

Looking at telnet the LUA coming in shows
gma.canbus.hardkey("0", true, false)
gma.canbus.hardkey("0", false, false)

I'm not sure if this is due to different formatting of the telnet commands but the numerics, plus and please button are definitely not working from the streamdeck

**Comment by istnv** [comment]
Corrected in release for V3
