### ISSUE TITLE
Encoder Button not working

### ISSUE THREAD

**Issue by Jpax411** [bitfocus/companion-module-grandma2#8]
When using the encoder buttons it adds  " ", to the encoder value. 

![companion prob](https://user-images.githubusercontent.com/8553946/181200857-ea87fd3a-3f5b-4e1b-96a9-0f990c897f80.jpg)

**Comment by who2us** [comment]
please note the case sensitive true and false statements at the end of the Lua
![image](https://user-images.githubusercontent.com/44941214/194731465-4b842682-f8a9-4878-a8ec-b44de0a2b4f0.png)
a capital F and T should be used instead.

also the -1 is a half step to move a 0.1 step in Grandma please use -2 or 2 
I tested the -20 to move the integer a negative 1.0 step

I have personally tested this, and works on version 3.9.60.45

**Comment by who2us** [comment]
@josephdadams could you please update the module with the required fix please? much appreciated.

**Comment by vremm** [comment]
I have tested and confirmed that a capital F or T gets the command to work. 

In reference to the step move, is it possible to add in a custom step integer field?

**Comment by KSchloe** [comment]
Hey man! 

did you fix this problem? Would be a really nice addition with the new Streamdeck+ 

Yours Kris

**Comment by who2us** [comment]
> 

Hey @KSchloe yes i actually tested many variations on this, and this is the solution. just a capital letter :(

**Comment by josephdadams** [comment]
@who2us can you submit a pull request to fix it?

**Comment by KSchloe** [comment]
> > 
> 
> Hey @KSchloe yes i actually tested many variations on this, and this is the solution. just a capital letter :(

Can you please push a new revision? In Companion it's still the old one and If this works, it's a game changer in combination with the new streamdeck+.

**Comment by istnv** [comment]
This will be fixed in v3.0. There will also be a new press/release option for the encoders. The StreamDeck + knobs work this way.
